spring:
    application:
        name: mtr-admin
    http:
        multipart.enabled: true
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://localhost:5432/ArduinoDemo
        databaseName: ArduinoDemo
        serverName: localhost
        username: postgres
        password: postgres
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        properties:
            hibernate.hbm2ddl.auto: update
            hibernate.id.new_generator_mappings: true
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    mail:
        host: smtp.googlemail.com
        port: 587
        user: cybertechsystems2011@gmail.com
        password: cybis@ban
        protocol: smtp
        tls: true
        auth: true
        from: test@localhost